name: README Update

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Update README
        id: contibutors
        run: |
          chmod +x .github/workflows/scripts/readme.sh
          ./.github/workflows/scripts/readme.sh
        shell: bash

      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README [Automated]"
          file_pattern: README.md
          commit_author: GitHub Actions <actions@github.com>
